Models/Gateau.cs
namespace Exercice2Images.Models
{
    public class Gateau
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public string UrlImage { get; set; }
        public string Description { get; set; }
        public string Ingredients { get; set; }

        public Gateau(int id, string nom, string urlImage, string description, string ingredients)
        {
            Id = id;
            Nom = nom;
            UrlImage = urlImage;
            Description = description;
            Ingredients = ingredients;
        }
    }
}

Controllers/AccueilController.cs
using Microsoft.AspNetCore.Mvc;

namespace Exercice2Images.Controllers
{
    public class AccueilController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/GateauxController.cs
using Exercice2Images.Models;
using Microsoft.AspNetCore.Mvc;

namespace Exercice2Images.Controllers
{
    public class GateauxController : Controller
    {
        private readonly List<Gateau> _mesGateaux;
        public GateauxController()
        {
            _mesGateaux = new List<Gateau>()
            { new Gateau(0, "Volcan et dinosaures", "/images/Dinos.jpg", "Gâteau génoise vanille, ganache au chocolat blanc vanille (intérieur) et au chocolat au lait (extérieur), amandes effilées", "Farine, oeufs, sucre, crème 35%, chocolat blanc, chocolat au lait, café, amandes, etc. "),
            new Gateau(1, "Mouton mignon", "/images/Sheep.jpg", "Gâteau en couches aux couleurs de l'arc-en-ciel avec une dacquoise amandes, crème chantilly mascarpone", "Farine, oeufs, sucre, amandes, crème 35%, mascarpone, guimauve, etc."),
            new Gateau(2, "Ruche", "/images/Ruche.jpg", "Gâteau vanille, ganache au chocolat blanc et miel", "Farine, oeufs, sucre, crème 35%, chocolat blanc, colorant jaune, miel, etc."),
            new Gateau(3, "Chat", "/images/chat.jpg", "Gâteau damier, génoise chocolat et vanille, crème au beurre meringue italienne, recouvert de pâte à sucre", "Farine, oeufs, sucre, beurre, colorant, etc."),
            new Gateau(4, "Echiquier", "/images/Echiquier.jpg", "Gâteau vanille et chocolat, crème au beurre italienne au beurre d'arachides, recouvert de pâte à sucre", "Farine, oeufs, sucre, vanille, beurre, beurre d'arachides, etc."),
            new Gateau(5, "Funfetti", "/images/funfetti.jpg", "Gâteau pinata, génoise vanille, crème chantilly mascarpone", "Farine, oeufs, sucre, crème 35%, mascarpone, etc."),
            new Gateau(6, "Halloween", "/images/Halloween.jpg", "Tarte panna cotta au chocolat, biscuits oreo, araignées en chocolat, glaçage au sucre", "Farine, oeufs, beurre, sucre, crème 35%, chocolat, etc."),
            };
        }


        /// <summary>
        /// Méthode d'action qui permet d'afficher 
        /// une liste d'images passées en paramètres 
        /// à la vue.
        /// </summary>
        /// <returns>La vue Liste</returns>
        public ViewResult Liste()
        {

            ViewBag.Titre = "Mes gâteaux";

            return View(_mesGateaux);
        }

        /// <summary>
        /// Méthode d'action qui permet d'afficher les 
        /// ingrédiens (ou autre) d'un gâteau
        /// </summary>
        /// <param name="id">Identifiant du gâteau</param>
        /// <returns>La vue Details</returns>
        public ViewResult DetailsGateau(int id)
        {
            int idGateau = _mesGateaux.FindIndex(g => g.Id == id);

            string ingredientsGateau = _mesGateaux[idGateau].Ingredients;
            string urlGateau = _mesGateaux[idGateau].UrlImage;

            ViewBag.Titre = "Détails gâteau";
            // L'idéal serait de créer un ViewModel (classe)
            // qui sera le modèle de la vue Details.
            // On passera alors un objet de ce type (cette classe)
            // à la vue Details.
            // Nous verrons cela une autre fois... En attendant,
            // nous nous contenterons d'envoyer des données faiblement
            // typées à la vue Details.
            ViewData["ingredientsGateau"] = ingredientsGateau;
            ViewData["urlGateau"] = urlGateau;

            return View("Details");
        }
    }
}

Views/Accueil/Index.cshtml
@{
    ViewData["Titre"] = "Page d'accueil";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Titre"]</title>
</head>
<body>

    <h1>@ViewData["Titre"]</h1>

</body>

</html>

Views/Gateaux/Details.cshtml
@{
    var ingredientsGateau = ViewBag.ingredientsGateau;
    var urlGateau = ViewBag.urlGateau;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />

    <title>@ViewData["Titre"]</title>
</head>
<body>
    <div class="container">
        <h1 class="m-3">@ViewData["Titre"]</h1>

        <div class="row mx-2 mt-4">
            <div class="col-5">
                <img src=@urlGateau class="rounded-5 img-fluid" alt="Image de gâteau original" />
            </div>
            <div class="col-5">
                <h4>Ingrédients:</h4>
                <p>@ingredientsGateau</p>
            </div>
        </div>        
        
        <div class="row mx-2 mt-5">
            <a asp-controller="Gateaux" asp-action="Liste">Retour à la liste de gâteaux</a>
        </div>

    </div>

</body>

</html>

Views/Gateaux/Liste.cshtml
@model List<Exercice2Images.Models.Gateau>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />

    <title>@ViewData["Titre"]</title>
</head>
<body>
    <div class="container">

        <div class="row mb-2">
            <a asp-controller="Accueil" asp-action="Index">Retour à l'accueil</a>
        </div>

        <h1 class="m-3">@ViewData["Titre"]</h1>
        <div class="row mb-5">
            @foreach (var gateau in Model)
            {
                <div class="card mx-2 mt-2" style="width: 18rem; border-color:sandybrown">
                    <img src=@gateau.UrlImage class="rounded-5 img-fluid card-img-top mt-4" alt="Image de gâteau original">
                    <div class="card-body">
                        <h5 class="card-title">@gateau.Nom</h5>
                        <p class="card-text">@gateau.Description</p>
                        <a class="btn btn-outline-warning" asp-controller="Gateaux" asp-action="DetailsGateau" asp-route-id=@gateau.Id>Voir les ingrédients du gâteau @gateau.Nom</a>
                    </div>
                </div>

            }
        </div>
    </div>

</body>

</html>